### ISSUE TITLE
Setup for valet site or without php artisan server

### ISSUE THREAD

**Issue by DesarrollouCR** [sfreytag/laravel-vite-pwa#2]
Hello,

First thanks for a good solution... but we wants to use the above for valet site or we want's to use this for our hosted webiste on cPanel... we removing /public path and running that directly from the public folder... so it is always giving us error

The path of the provided scope ('/') is not under the max scope allowed ('/build/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.

Any suggestion.

**Comment by sfreytag** [comment]
I think your problem is common to everyone using Laravel, no matter the deployment. My fix is to use the Service-Worker-Allowed header as per here for local development: https://github.com/sfreytag/laravel-vite-pwa/blob/main/server.php

For production I added it to the nginx config:

```
location /build/sw.js {
    add_header Service-Worker-Allowed "/";
}
```

In cPanel I guess you'd do something similar for Apache with .htaccess?

**Comment by DesarrollouCR** [comment]
First Thanks for your fast reply...

Service worker is not installed on production...

But it is working when I run using php php artisan serve

 
![Screenshot-2024-10-12-at-7-12-25-PM-10-12-2024_07_13_PM](https://github.com/user-attachments/assets/3d99c33d-32cc-4234-ac7e-d52172d0fd4f)

**Comment by sfreytag** [comment]
If it works with artisan then the fix is definitely the header for the sw.js file. Have a look in the network tab for the request for `/build/sw.js` and see if you've got the Accept-Service-Worker header in the response?

If not, you need to work out how to get it in there. I think supporting various prod configs is beyond the scope of this repo, but it would be good to begin documenting them too, so if you work it out let me know and I'll add some docs including my nginx snippet above.

**Comment by vesper8** [comment]
I'm very confused by this. I tried adding 

```

location /build/sw.js {
    add_header Service-Worker-Allowed "/";
}
```

As well as many variants of the above.. and while it got rid of the scope error, it would just result in a 404 on the /build/sw.js

This was both when using Laravel Valet and when using Laravel Forge.

In both cases just adding 
```
add_header Service-Worker-Allowed "/";
``` 
near the top, outside of a location block, seemed to solve the problem. I have a feeling I shouldn't be doing it this way, but I don't understand why doing it inside of a location block wouldn't work.
